runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
instance_class: F2
service: default
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
